project_id = "qxizqlbrapcnwzpvqplt"

[functions.delete-user]
verify_jwt = false

[functions.get-email-by-username]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.set-new-password]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.send-dm-notification]
verify_jwt = false
